### ISSUE TITLE
Neo Mousekeys' grid only accepts wasd, not hjkl

### ISSUE THREAD

**Issue by brimwats** [petoncle/mousemaster#1]
Setttings:

```
# Grid is enabled with g, disabled with g or esc.
# Press direction keys to shrink the grid in one direction.
normal-mode.to.grid-mode=+grid
grid-mode.to.normal-mode=+grid | +esc
grid-mode.to.idle-mode=+exit
grid-mode.grid.area=active-screen
grid-mode.grid.area-width-percent=0.99
grid-mode.grid.area-height-percent=0.99
grid-mode.grid.synchronization=mouse-follows-grid-center
grid-mode.grid.line-visible=true
grid-mode.grid.line-color=#FF0000
grid-mode.shrink-grid.up=+up
grid-mode.shrink-grid.down=+down
grid-mode.shrink-grid.left=+left
grid-mode.shrink-grid.right=+right

# Hints are enabled with f, disabled with f or esc.
# Holding leftshift while selecting the hint will trigger a second hint pass with a smaller hint grid
# centered around the mouse to refine the position.
normal-mode.to.hint1-mode=+hint
hint1-mode.to.normal-mode=+esc | +backspace
hint1-mode.to.idle-mode=+exit
hint1-mode.hint.type=grid
hint1-mode.hint.grid-area=active-screen
hint1-mode.hint.active-screen-grid-area-center=screen-center
hint1-mode.hint.grid-cell-width=72
hint1-mode.hint.grid-cell-height=40
hint1-mode.hint.undo=backspace
hint1-mode.hint.mode-after-selection=normal-mode

hint1-mode.to.hint2-1-mode=+slow
# leftshift (slow key) is already pressed in slow mode.
slow-mode.to.hint2-1-mode=+hint
hint2-1-mode.hint=hint1-mode.hint
hint2-1-mode.to.hint1-mode=-slow
hint2-1-mode.to.idle-mode=+exit
hint2-1-mode.hint.mode-after-selection=hint2-2-mode

hint2-2-mode.to.idle-mode=+exit
hint2-2-mode.to.hint1-mode=+backspace
hint2-2-mode.to.normal-mode=+esc
hint2-2-mode.hint=hint1-mode.hint
hint2-2-mode.hint.type=grid
hint2-2-mode.hint.grid-area=active-screen
hint2-2-mode.hint.active-screen-grid-area-center=mouse
hint2-2-mode.hint.grid-max-row-count=4
hint2-2-mode.hint.grid-max-column-count=5
hint2-2-mode.hint.grid-cell-width=22
hint2-2-mode.hint.grid-cell-height=17
hint2-2-mode.hint.selection-keys=h j k l ; a s d f g q w e r t y u i o p z x c v b
hint2-2-mode.hint.font-size=8
hint2-2-mode.hint.mode-after-selection=normal-mode
```

in vscode everything after ; is greyed out, but editing doesn't seem to do anything. 
![image](https://github.com/petoncle/mousemaster/assets/73113656/fe9fd511-ec35-4c22-9f11-f3c64957addf)

trying to use hjkl in grid mode but only wasd works there. Any ideas?

**Comment by petoncle** [comment]
Hi @brimwats, thanks for the feedback.

If you want to change the grid keys which are currently the same as the move keys (wasd), then you need to change this part:
```properties
grid-mode.shrink-grid.up=+up
grid-mode.shrink-grid.down=+down
grid-mode.shrink-grid.left=+left
grid-mode.shrink-grid.right=+right
```
to:
```properties
grid-mode.shrink-grid.up=+k
grid-mode.shrink-grid.down=+j
grid-mode.shrink-grid.left=+h
grid-mode.shrink-grid.right=+l
```

The part that you've tried to change is related to the hints, and it does not affect the grid.

**Comment by brimwats** [comment]
Ahhh that was an obvious one I missed! Thank you for pointing that out! I hope it's at least helpful for documentation writing

While i'm here though,  am I right in (now) understanding that the `hint2-2-mode.hint.selection-keys=h j k l ; a s d f g q w e r t y u i o p z x c v b` is for the hints that appear on the screen after pressing `f`? 

I tried modifying that line to see if I could get it to be only keys that appear on the right hand side of a spit keyboard (i've mapped moustmaster to a [razer tartarus ](https://www.razer.com/ca-en/gaming-keypads/razer-tartarus-pro) with good success, but it didn't seem to work so I mist have misunderstood again!

**Comment by brimwats** [comment]
It's probably worth mentioning that my original confusion happened because of the line in the documentation that says "Shrink the grid in one direction with h, j, k, l."; it sounds like it actually is w a s d unless set in the aliases, yes?

**Comment by petoncle** [comment]
> I hope it's at least helpful for documentation writing

Definitely. Thank you so much for asking those questions and sharing your feedback! 

You're correct about the hints. In the neo-mousekeys configuration I have implemented 2-pass hints. The second pass is optional and is for refining the mouse position further in case the first hint pass was not precise enough. Like you've discovered, the second pass is triggered if you hold leftshift while selecting the hint of the first pass.

> i've mapped moustmaster to a [razer tartarus](https://www.razer.com/ca-en/gaming-keypads/razer-tartarus-pro)

Interesting keyboard, I'll have to look into it!

> It's probably worth mentioning that my original confusion happened because of the line in the documentation that says "Shrink the grid in one direction with h, j, k, l."; it sounds like it actually is w a s d unless set in the aliases, yes?

You are 100% correct, I made a mistake in the [documentation](https://github.com/petoncle/mousemaster/blob/main/configuration/neo-mousekeys.md). Sorry about that. I will fix it.

By the way, I'm not personally using this configuration (neo-mousekeys) but I believe it is appropriate for most people, that's why I present it as the *recommended* configuration. The fact that I'm not using it also means that I have not spent as much time fine tuning it as I did for my personal configuration.  
Besides potential bugs in this configuration, there are things that could be improved. Two examples:
1. In my personal config, I have a way to choose if I want the grid to cover the entire screen or the active window. Currently in the neo-mousekeys config, the grid can only cover entire screen. I actually use the active window grid quite a lot, so it may be a good idea to add it into the neo-mousekeys config. I think I'd need to hear about other people's thoughts.
2. In my personal config, the hint mode is more advanced: I can do things like select a hint then automatically trigger a left button click.

If you have any suggestions for improving that configuration, let me know.

Anyway, thanks again for the feedback! ❤️

**Comment by petoncle** [comment]
> I tried modifying that line to see if I could get it to be only keys that appear on the right hand side of a spit keyboard (i've mapped moustmaster to a [razer tartarus ](https://www.razer.com/ca-en/gaming-keypads/razer-tartarus-pro)with good success, but it didn't seem to work so I mist have misunderstood again!

I missed replying to that. Did you manage to change the hint keys for the first hint pass?

**Comment by brimwats** [comment]
> You're correct about the hints. In the neo-mousekeys configuration I have implemented 2-pass hints. The second pass is optional and is for refining the mouse position further in case the first hint pass was not precise enough. Like you've discovered, the second pass is triggered if you hold leftshift while selecting the hint of the first pass.
> ...
> I missed replying to that. Did you manage to change the hint keys for the first hint pass?

No matter what they're changed to it doesn't seem to affect the grid. I still see this; 

![image](https://github.com/petoncle/mousemaster/assets/73113656/871ae865-5b0f-43b0-8c9f-1b2a2731ab8a)

> By the way, I'm not personally using this configuration (neo-mousekeys) but I believe it is appropriate for most people, that's why I present it as the _recommended_ configuration. 

I think a wasd configuration is the correct for most people, yeah. However, as you note

> The fact that I'm not using it also means that I have not spent as much time fine tuning it as I did for my personal configuration. Besides potential bugs in this configuration, there are things that could be improved. Two examples:
> 
> 1. In my personal config, I have a way to choose if I want the grid to cover the entire screen or the active window. Currently in the neo-mousekeys config, the grid can only cover entire screen. I actually use the active window grid quite a lot, so it may be a good idea to add it into the neo-mousekeys config. I think I'd need to hear about other people's thoughts.

There are some issues like this on a vertical screen:
![image](https://github.com/petoncle/mousemaster/assets/73113656/a687e9a1-606b-4af7-8219-dbb93f0a3b91)



> 2. In my personal config, the hint mode is more advanced: I can do things like select a hint then automatically trigger a left button click.

This would be fantastic! As it stands I currently use Fluent Search's screen search feature. The settings look like this:

![image](https://github.com/petoncle/mousemaster/assets/73113656/bfae18a8-842d-46d4-ac3b-9e6d6fdc86f6)

Documentation: https://fluentsearch.net/posts/fluent-search-features-guide 

Their code is open source iirc so maybe you can take some inspiration from that?

**Comment by petoncle** [comment]
Hi @brimwats,

Let me try to explain how hints work and from there we'll try to resolve the problems you've had.

In the neo-mousekeys config, there are 3 modes that define a hint grid: hint1-mode which is for single-pass hints, hint2-1-mode which is for the first pass of 2-pass hints, and hint2-2-mode which is for the second pass of 2-pass hints.

The hints are defined by a few things, mostly:
1. The hint selection keys (customizable with hint.selection-keys=...), which, when unspecified, default to: a b c d e f g h i j k l m n o p q r s t u v w x y z
2. The spacing between each hint defined indirectly via the size of the grid cells (customizable with hint.grid-cell-width and hint.grid-cell-height) which defaults to: 72 pixels (width) and 40 pixels (height). These default values are for getting the following layout on a 1920x1080 screen:
    ```
    AA BA ... ZA
    AB BB ... ZB
    ...
    AZ BZ ... ZZ
    ```
3. The maximum number of rows and columns (customizable with hint.grid-max-row-count and hint.grid-max-column-count) which defaults to: 26 and 26. The reason I've implemented a max number of rows and columns is for the second hint pass which is a smaller hint grid that needs only a few hints around the cursor. 

I think I got the default wrong for 3. (max number of rows and columns). I can't think of a reason for limiting it to 26. That is why in your screenshot, only a portion of the screen is covered by hints.  I've increased the default to 100 for now (that way, you don't need to change the config file) and created a new release: [v1.0.31](https://github.com/petoncle/mousemaster/releases/latest). You'd only need the new executable (mousemaster.exe).

Now, let's tackle the problem you have with changing the hint keys. We have 3 hint modes in the neo-mousekeys config:
- hint1-mode uses the default hint keys, which is equivalent to:
```properties
hint1-mode.hint.selection-keys=a b c d e f g h i j k l m n o p q r s t u v w x y z
```
- hint2-1-mode inherits the properties of hint1-mode, that is the purpose of this line:
```properties
hint2-1-mode.hint=hint1-mode.hint
```
- hint2-2-mode -- which is the smaller hint grid (second hint pass) -- uses the following hint keys:
```properties
hint2-2-mode.hint.selection-keys=h j k l ; a s d f g q w e r t y u i o p z x c v b
```

If you want to change the hint keys of the first pass, you should be able to do that by adding a line like:
```properties
hint1-mode.hint.selection-keys=q w e r t y 1 2 3 4 5
```
With this, both hint1-mode and hint2-1-mode will use the selection keys you specify.

> As it stands I currently use Fluent Search's screen search feature.

For some reason I never heard of Fluent Search before. It looks very cool. I see that it does context-aware hints which has both benefits and drawbacks (when compared to "dumb hints" that cover the whole screen). Context-aware hints only show hints above actual app widgets (buttons, textboxes, menus, etc.) which reduce the clutter (no unnecessary hints), but on the other hand they don't always allow you to move the mouse exactly where you want it to move. That's the reason why I did not look into context-aware hints (yet).  

For my reference: when selecting a hint in Fluent Search, you can press 1, 2, 3, or 4 to choose whether you want a left button click, double left button click, left button press and hold, or right button click. In mousemaster, we have the bricks we need to implement these purely in the configuration file, except for the double click: we have commands for pressing a mouse button and releasing it (PressLeft and ReleaseLeft).

In my config (which is optimized for a single hand usage), this is how I currently do clicking after selecting a hint: assuming there are a bunch of hints on the screen, if I want to select the one labelled `HJ`, then I press `H` then `J` which selects the hint, moves the mouse and presses the left mouse button. If I want to double click, I press `H` then `J`, then `J` a second time. That works fine in my config because I can do everything with one hand, but I am wondering if the Fluent Search approach (press another key like 1/2/3/4 before selecting the hint to choose what kind of click behavior you want) would be better for the recommended mousemaster config.

Question for you @brimwats: how do you find the default activation combo (ctrl + e)? I know that it's not ideal since many apps use that combo. I'm also wondering if we need a combo to go directly to grid mode and hint mode. Currently, if you want to go to grid mode you need to first go to normal mode (ctrl + e), then grid mode (g); same for hint mode (ctrl + e, then f). 

As always, thank you again for the very useful feedback, and for introducing me to Fluent Search.

**Comment by brimwats** [comment]
=Sorry for the delay! I wanted to get some experience using the app! 

First a couple of questions! 

1. I wanted an indicator for when MM was not active, so I added a couple lines to the config:

```
idle-mode.to.normal-mode=_{leftctrl} +e
idle-mode.indicator.enabled=true
normal-mode.indicator.enabled=true
idle-mode.indicator.mouse-press-color=#b0b0b0
idle-mode.indicator.idle-color=#b0b0b0
normal-mode.indicator.idle-color=#00ff00
normal-mode.indicator.move-color=#ff00ff
normal-mode.indicator.mouse-press-color=#FF0000
```
I wanted it to be grey. However there is some blue flickering when I type that I cant figure out where it is coming fyorom:

![vivaldi_ItkHPY7siW](https://github.com/petoncle/mousemaster/assets/73113656/ecee1c9b-70d7-45c7-86ed-65b03fca7bc5)


----

Now your questions!

1. This

```
hint1-mode.hint.grid-max-row-count=45
hint1-mode.hint.grid-max-column-count=26
hint1-mode.hint.grid-cell-width=72
hint1-mode.hint.grid-cell-height=42
```

works on both a vertical and horizontal screen well!

2. setting `hint1-mode.hint.selection-keys=7 8 9 0 y u i o p h j k l n m` works for when i use the razer and better generally. I haven't tried `[ ] ; ' , . /` would those be accepted?


3. 
> But I am wondering if the Fluent Search approach (press another key like 1/2/3/4 before selecting the hint to choose what kind of click behavior you want) would be better for the recommended mousemaster config. If you have any comment/suggestion about that, let me know.

I haven't used the multi click features of FS too much, generally I just use it to jump from one screen to another (you hit shift and it switches to another screen. To give you an idea of what I have, I have a 27" landscape middle screen, a 24" lanscape screen above it and 2x vertical 24" screens to the left and right. A lot of screenspace! A key to jump to the next/previous monitor in this context would be good. Here's how DisplayFusion does it: (I don't know what code they use to do this, but it's s scripted function within DF)

```
using System;
using System.Drawing;

public static class DisplayFusionFunction
{
	public static void Run()
	{
		BFS.DisplayFusion.RunFunctionAndWait("Move Mouse Cursor to Next Monitor");
		BFS.DisplayFusion.RunFunctionAndWait("Move Mouse Cursor to Center of Current Monitor");
	}
}
```


4. Otherwise, so far m y biggest pain point with MM switching on and off is that I will often start typing and forget MM is active. I haven't checked the documentation to see if it can be autodisabled when (f.ex.) I switch to vivaldi, which has vimium-c and doesn't need MM. I also feel like the ctrl-e hotkey should be a toggle to turn it on and off, not just a on button. I currently have `key-alias.exit=q p` set and  the q is a much better setting for qwerty imo. I need to explore the settings a bit more but I'm in the middle of a big move so havent and I apologize if any of this is needless info!

**Comment by petoncle** [comment]
Hello!

> 1. I wanted an indicator for when MM was not active, so I added a couple lines to the config (...) However there is some blue flickering when I type that I cant figure out where it is coming from

Ah! I had implemented something to change the color of the indicator when a key unhandled by mousemaster is being pressed. This is exactly what happens when you type. I realize now that this feature is weird and can be confusing. I should probably not make the default do that? By default, when pressing an unhandled key, the indicator color changes to blue:
```properties
idle-mode.indicator.unhandled-key-press-color=#0000FF
```

> 2. setting `hint1-mode.hint.selection-keys=7 8 9 0 y u i o p h j k l n m` works for when i use the razer and better generally. I haven't tried `[ ] ; ' , . /` would those be accepted?

Yes `[ ] ; ' , . /` would work too (I've just tried it). Do you think I should change it in the neo-mousekeys configuration to `7 8 9 0 y u i o p h j k l n m`? What about the second pass of the hint selection with the smaller hint grid?

> 3. I haven't used the multi click features of FS too much, generally I just use it to jump from one screen to another (you hit shift and it switches to another screen. 

What we can do right now in mousemaster is defining a screen hint selection mode. It would be a mode where one giant hint is displayed on each screen, like so:
![java_ZE2NKpPpt0](https://github.com/petoncle/mousemaster/assets/39304282/a8f59d0b-b697-4f6a-b37f-5b7bd47b57a2)

It would be easy to add to the neo-mousekeys configuration. I just need to figure out what would be the best way to enter that screen selection mode. Should it be enterable from the idle mode, or from the normal mode (i.e. after pressing `ctrl + e`), or both? And then, what key/key combo to use to enter it? Any ideas :thinking:?
Would that work, or do you think it would still be inferior to cycling through screens? I could also try to implement a new cycle-through-screens command (next/previous screen).

> 4. Otherwise, so far m y biggest pain point with ctrl-e MM switching on and off is that I will often start typing and forget MM is active. I haven't checked the documentation to see if it can be autodisabled when (f.ex.) I switch to vivaldi, which has vimium-c and doesn't need MM. 

That's an excellent point. The idea would be to auto-disable when specific programs (e.g. firefox.exe or vivaldi.exe) are active. I'll need to think about it and see if I can implement it.

> 5. I also feel like the ctrl-e hotkey should be a toggle to turn it on and off, not just a on button. 

That can be done easily. I should add it to the neo-mousekeys configuration. Basically, replace:
```properties
normal-mode.to.idle-mode=+exit | -clickthendisable
```
with:
```properties
normal-mode.to.idle-mode=+exit | -clickthendisable | _{leftctrl} +e
```
With that you could use `leftctrl + e` to turn it off.

> 6. I currently have key-alias.exit=q p set and the q is a much better quit setting for qwerty imo. 

Ok, I will change the current exit keys (`capslock` and `p`) to `q` and `p`.

> 7. as far as other programs, it only bothers me in word (center text) and so I have to go crtl e ctrl e q and Directory Opus, but I just changed the dopus setting.

If you have any suggestions for replacing `ctrl + e` with something better, I'm all ears! Maybe a key combo that uses `alt` instead of `ctrl`? We can do advanced key combos like pressing a key twice in a row, or pressing a key for a minimum amount of time. I worked hard on key combos so that anything can be done, really.

> I need to explore the settings a bit more but I'm in the middle of a big move so havent and I apologize if any of this is needless info!

I only see useful info here :blush:. Thanks so much for the feedback!

**Comment by brimwats** [comment]
1. 
> Do you think I should change it in the neo-mousekeys configuration to 7 8 9 0 y u i o p h j k l n m? What about the second pass of the hint selection with the smaller hint grid?

imo def no, most people would want the range you have right now. I think the second pass is the sane and reasonable choice for most people; if you want a smaller selection using just the home row `asdfghjkl;` would make the most sense

2,
> idle-mode.indicator.unhandled-key-press-color=#0000FF

works perfect!

3.
> What we can do right now in mousemaster is defining a screen hint selection mode. It would be a mode where one giant hint is displayed on each screen, like so:
 
WOW that is SO COOL i love it! that's just a neat feature in general! big +1 from me

4. 
> . I just need to figure out what would be the best way to enter that screen selection mode. Should it be enterable from the idle mode, or from the normal mode (i.e. after pressing ctrl + e), or both? And then, what key/key combo to use to enter it? Any ideas 🤔?

This is where we run into limitations with common hotkeys! I think crtl+alt `letter` is what most programs are doing these days as microsoft and others take over more of the standard ctrl + `letter` keys. so what about `ctrl + alt g` for "grid"  and c+a+h for hint? ctrl + e seems like a good fit for a default (imo) as I use quite a lot of hotkeys and for only DOPUS and Word to be using ctrl e is pretty good. 

If you ever want a peep at programs defaults, get an account at https://keycombiner.com (free) and poke around their big program libraries (like word, vscode, etc).

5. 
> That's an excellent point. The idea would be to auto-disable when specific programs (e.g. firefox.exe or vivaldi.exe) are active. I'll need to think about it and see if I can implement it.

Seems the solution would be something like what Alt+Snap or others do (aka using Autohotkey window types using Window Spy (https://amourspirit.github.io/AutoHotkey-Snippit/WindowSpy.html).l So here's what that looks like in AHK for a script that _only_ runs on a matching window

```ahk

; Auto-execute section.
Hotkey, %f_Hotkey%, f_Jump2ActivePath
;Hotkey, %f_HotkeyCombo%, f_Jump2ActivePath
return 

f_Jump2ActivePath:
;validate the correct dialogue type
WinGet, f_window_id, ID, a
WinGetClass, f_class, a
; Don't display menu unless it's a dialog or console window
if f_class not in #32770,ConsoleWindowClass
return
```

6. 
> normal-mode.to.idle-mode=+exit | -clickthendisable | _{leftctrl} +e

Will give it a spin!

**Comment by petoncle** [comment]
I've implemented some of the things we've been talking about:

1. Made _leftctrl + e_ toggle normal mode on and off.
2. Changed deactivation keys to q and p.
3. Defined a screen selection mode (_c_ in normal mode). I'm not too sure if _c_ is the best 
4. Ensured screens are sorted by position for all-screens hints determinism.

1., 2., and 3. are purely configuration changes (see what changed in [neo-mousekeys.properties](https://github.com/petoncle/mousemaster/commit/08deed27ba254e864dfb7b6763979e3f122b2be9#diff-3a955cf6a48b5672acd0c68285ffb12f280d5fd08c40759b6fe3bbaba67100b1) for the new screen selection mode). 
4. is a code change that will require you to download [the new _mousemaster.exe_ executable](https://github.com/petoncle/mousemaster/releases/latest).

I've also updated the [neo-mousekeys documentation](https://github.com/petoncle/mousemaster/blob/main/configuration/neo-mousekeys.md):

![neo-mousekeys layout](https://github.com/petoncle/mousemaster/assets/39304282/c1648953-8acb-49e3-abb5-8106b7502105)

**Comment by brimwats** [comment]
This is so great! It is working well initially, take it for more of a spin over this week.

Thinking through other features that all layouts might be able to use; I'm not sure how 'smart' the commands are, but potential ideas:
1. a button that goes to the middlle of the current window's frame and grabs it (for moving/dragging)
2. does MM know where the min max close ➖⏹️✖️ buttons are? those are pretty common buttons that would make sense to have as "default optional" items.

**Comment by petoncle** [comment]
> This is so great! It is working well initially, take it for more of a spin over this week.

Good to hear! Let me know how it goes!

> Thinking through other features that all layouts might be able to use; I'm not sure how 'smart' the commands are, but potential ideas:
>     1. a button that goes to the middlle of the current window's frame and grabs it (for moving/dragging)

I think I'm able to do something like that in my config. I can snap the cursor to the active window's center and edges, and for the top edge I've used an inset so that the cursor lands inside the window's title bar (and not right on the edge). It looks like this:

https://github.com/petoncle/mousemaster/assets/39304282/105c6a2d-2849-4d23-b706-1fc9410ae680

Is that roughly what you are talking about?

Note: in this video, I grab the edges and then move them around (resize) using the grid mode. I also select the title bar and move it around using the grid mode.

> 2. does MM know where the min max close ➖⏹️✖️ buttons are? those are pretty common buttons that would make sense to have as "default optional" items.

Unfortunately, it doesn't know about where these buttons are. However, Windows has built-in shortcuts which I personally use all the time to minimize/maximize/close a window, not sure if they're good for you too?
- Minimize: alt + space, then n
- Maximize: alt + space, then x
- Restore (i.e. undo a maximize): alt + space, then r
- Close: alt + space, then c (or alt + f4)

**Comment by brimwats** [comment]
So bad news for the ctrl-e command. 

> https://www.windowscentral.com/software-apps/windows-11/windows-11-build-26052-everything-you-need-to-know
> The new option allows you to ask Copilot directly to help you understand programming code, log files, or any selected text without extracting the extra steps of copying, opening Copilot, and pasting the text in the prompt.  The feature integration even offers the "Ctrl + E" keyboard shortcut to send the content directly to Copilot.

Microsoft is starting to use that (notepad and some other windows apps only right now)

> I think I'm able to do something like that in my config. I can snap the cursor to the active window's center and edges, and for the top edge I've used an inset so that the cursor lands inside the window's title bar (and not right on the edge). It looks like this:

omg that is *extremely* cool! yes, that's exactly what I was thinking of


> Unfortunately, it doesn't know about where these buttons are. However, Windows has built-in shortcuts which I personally use all the time to minimize/maximize/close a window, not sure if they're good for you too?

🤯🤯 it has been a *long time* since someone has told me a shortcut I didn't know about, and to find out about alt+space this way! I've been using that for a long time for quick launchers like karabiner, fluid, launchy, and listary. Now I have to do some thinking about if I keep it as "search apps" for fluent or not! 

I've had some success combining Alt+Snap  https://github.com/RamonUnch/AltSnap with mousemaster, in case you were curious about tools that can be used with MM!

**Comment by petoncle** [comment]
> So bad news for the ctrl-e command.
> 
> > https://www.windowscentral.com/software-apps/windows-11/windows-11-build-26052-everything-you-need-to-know
> > The new option allows you to ask Copilot directly to help you understand programming code, log files, or any selected text without extracting the extra steps of copying, opening Copilot, and pasting the text in the prompt.  The feature integration even offers the "Ctrl + E" keyboard shortcut to send the content directly to Copilot.
> 
> Microsoft is starting to use that (notepad and some other windows apps only right now)

Good catch! I always thought Ctrl + E was not ideal for mousemaster. I could definitely not use it myself as it's a default key combo in my IDE (IntelliJ) which I use dozens of times a day.
 
> > I think I'm able to do something like that in my config. I can snap the cursor to the active window's center and edges, and for the top edge I've used an inset so that the cursor lands inside the window's title bar (and not right on the edge). It looks like this:
> 
> omg that is _extremely_ cool! yes, that's exactly what I was thinking of

Great. I'm trying to think of an ergonomic/intuitive way to introduce it in the neo-mousekeys config. I think it should be a key that you press and hold. As soon as you press it, the mouse is moved to the center of the active window. Then, while still holding that key, you can snap the cursor to the edges of the window using the direction keys.

> 
> > Unfortunately, it doesn't know about where these buttons are. However, Windows has built-in shortcuts which I personally use all the time to minimize/maximize/close a window, not sure if they're good for you too?
> 
> 🤯🤯 it has been a _long time_ since someone has told me a shortcut I didn't know about, and to find out about alt+space this way! I've been using that for a long time for quick launchers like karabiner, fluid, launchy, and listary. Now I have to do some thinking about if I keep it as "search apps" for fluent or not!

Isn't Karabiner macOS only? Never heard of fluid and listary before, I'll look them up!

> I've had some success combining Alt+Snap https://github.com/RamonUnch/AltSnap with mousemaster, in case you were curious about tools that can be used with MM!

Looks very useful, I'm going to have to try it out. Thanks for sharing!

**Comment by petoncle** [comment]
Hi @brimwats, sorry for the delay! I've added a new window mode that does what we were talking about:

#### Window Mode (hold _leftshift_ then press _g_ in normal mode)

- Move mouse to the active window's edges with direction keys.
- Move mouse to the center of the active window with _g_.
- Go back to normal mode by releasing _leftshift_.
 
I'm not sure if these keys are intuitive or not for that feature, you tell me if you have a chance to try it.  
It's purely a configuration change in [neo-mousekeys.properties](https://github.com/petoncle/mousemaster/blob/760cc77c5a7923c09774a10ac06507f77e391a75/configuration/neo-mousekeys.properties#L189-L208) where a new mode (`window-mode`) has been added. I've also created a new release ([v1.0.37](https://github.com/petoncle/mousemaster/releases/latest)) for this.

**Comment by brimwats** [comment]
Thanks! Cant wait to try it out. FYI that something in this release is triggering Defender:
![image](https://github.com/petoncle/mousemaster/assets/73113656/843518b0-1e31-46d5-bdae-df536c17d5f8)

**Comment by brimwats** [comment]
First initial feedback! 

I think these

```
hint1-mode.hint.selection-keys=7 8 9 0 y u i o p h j k l n m
hint2-2-mode.hint.selection-keys=y u i o p h j k l ; n m
screen-selection-mode.hint.selection-keys=j k l ; a s d f g
```
(or whatever their default values) should be in the top of the config file bc otherwise folks will have to go through the new config file side by side with the old one

**Comment by petoncle** [comment]
> Thanks! Cant wait to try it out. FYI that something in this release is triggering Defender: 

Thanks for letting me know. Very strange, my Windows doesn't complain about it.
I've sent it to VirusTotal for analysis, [the results look fine (2/73)](https://www.virustotal.com/gui/file/e812b34378f59cc8e3d175e3187fc9c61ec08096a41f428b4e7f2ef949ac5b9a?nocache=1).

I'm not sure what is triggering the alert you got. The good thing is that the _mousemaster.exe_ build from the release page is fully automated and run on GitHub's VMs (it's not built from my machine). There would need to be malicious code in the code repository for it to end up in _mousemaster.exe_.

**Comment by brimwats** [comment]
Yeah I'm not worried about it, more an FYI for you in case others report it!

**Comment by brimwats** [comment]
> Window Mode (hold leftshift then press g in normal mode)

This doesn't work.. I suspect because g is taken by grid and there's no window-mode key-alias?
```
key-alias.grid=g
key-alias.hint=f
```

**Comment by petoncle** [comment]
> > Window Mode (hold leftshift then press g in normal mode)
> 
> This doesn't work.. I suspect because g is taken by grid and there's no window-mode key-alias?
> 
> ```
> key-alias.grid=g
> key-alias.hint=f
> ```
> 
> edit: ah! got it, it wasn't clear that WASD were the keys I should be pressing (I read direction keys as arrow keys!

Ah yes, you're right, that part is unclear. 

> I think these
> ```
> hint1-mode.hint.selection-keys=7 8 9 0 y u i o p h j k l n m
> hint2-2-mode.hint.selection-keys=y u i o p h j k l ; n m
> screen-selection-mode.hint.selection-keys=j k l ; a s d f g
> ```
> (or whatever their default values) should be in the top of the config file bc otherwise folks will have to go through the new config file side by side with the old one

Good point too.

**Comment by brimwats** [comment]
I think we can safely close this one now :)
